# -*- coding: utf-8 -*-
"""life_games

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d2GnxiViJuCq2cA6WqzuTJdgTln1Usnc
"""

class pycolor:
    RED = '\033[31m'
    END = '\033[0m'


# クラスPersonを作成
class Person(object):
    def __init__(self, name="名無しさん", hapiness=10, ability=5, skill=1):
        self.name = name
        self.hapiness = hapiness
        self.ability = ability
        self.skill = skill

    
# 勉強
    def study(self):
        print("めんどくさいけど勉強するぞ！")
        self.ability += 0.5
        self.hapiness -= 5
        print("幸せ度{}point、能力は{}pointになった。".format(self.hapiness, self.ability))
        print("辛かったけど、能力はついた！")

# 稼ぐ
    def earn(self):
        print("ヨッシャ稼ぐぞおおおお！")
        self.hapiness += 1 * self.ability
        print("幸せ度{}point、能力は{}pointになった。".format(self.hapiness, self.ability))
        print("お金で買える幸せもある！")

# 遊ぶ
    def play(self):
        print("遊ぶぞおおお！勉強なんて知らん！")
        self.ability -= 1
        self.hapiness += 2 * self.ability
        print("幸せ度{}point、能力は{}pointになった。".format(self.hapiness, self.ability))
        print("遊んでいると幸せになれる泣")

# 賭ける    
    def bet(self):
        import random
        print("一発逆転しかない！")
        self.hapiness += random.randint(-20, 20)
        print("幸せ度{}point、能力は{}pointになった。".format(self.hapiness, self.ability))
        print("運というのは大事な要素の1つ。何も言えねぇ")

# 何もしない
    def boring(self):
        print("もう何もしたくなーい")
        self.ability -= 0.5
        self.hapiness -= 5
        print("幸せ度{}point、能力は{}pointになった。".format(self.hapiness, self.ability))
        print("人生の中で1番無駄な事は、何もしない事。行動をしなければ")

# スタティックメソッドで定型文を書く
    @staticmethod
    def explain_contents():
        print("あなたはどんな人ですか？下からお選びください（下記以外の言葉にすると「究極の凡人」になります）")
        print("↓↓↓↓↓↓↓↓↓↓↓コピペして使ってね↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓")
        print(pycolor.RED + "・究極の凡人(スキル「凡人の意地」）" +pycolor.END)
        print(pycolor.RED + "・通りすがりの天才（スキル「覚醒」）"+pycolor.END)
        print(pycolor.RED +"・幸せ者（スキル「好きなことで生きていく」）"+pycolor.END)



# クラスCommonPersonを作成（Person継承）
class CommonPerson(Person):
    def __str__(self):
        return '''わいの名前は {}!!究極の凡人でも幸せになるぞおおお
現在は、幸せ度{}point、能力は{}pointあるよ！'''.format(self.name, self.hapiness, self.ability)
    
    def skill_something(self):
        print("***********************************************{}の「凡人の意地」発動！***************************************************************".format(person.name))
        print("「普通」とは最上級の褒め言葉！")
        self.ability += 1
        print("能力が１上がった！！")    
        print("幸せ度{}point、能力は{}pointになった。".format(self.hapiness, self.ability))  


# クラスGeniusPersonを作成（Person継承）
class GeniusPerson(Person):
    def __str__(self):
        return '''僕の名前は {}!!　自分の力を確かめたいんだ！
現在は、幸せ度{}point、能力は{}pointあるよ！'''.format(self.name, self.hapiness, self.ability)
    
    def skill_something(self):
        import random
        print("***********************************************{}の「覚醒」発動！***************************************************************".format(person.name))
        print("ようやく分かった！天才という事に！！")
        ran = random.randint(1, 50)
        self.hapiness += ran
        print("幸せ度が{}上がった！！".format(ran)) 
        print("幸せ度{}point、能力は{}pointになった。".format(self.hapiness, self.ability)) 


# クラスHappyPersonを作成（Person継承）
class HappyPerson(Person):
    def __str__(self):
        return '''僕の名前は {}!!　もう既に幸せだけどもっと幸せになる！
現在は、幸せ度{}point、能力は{}pointあるよ！'''.format(self.name, self.hapiness, self.ability)

    def skill_something(self):
        import random
        print("***********************************************{}の「好きなことで生きていく」発動！***************************************************************".format(person.name))
        print("ブン●ン！ハロー！")
        ran = random.randint(-30, 100)
        self.hapiness += ran
        print("幸せ度に{}pointが付与された".format(ran)) 
        print("幸せ度{}point、能力は{}pointになった。".format(self.hapiness, self.ability))       


# ここから開始
print("このゲームには説明書があります。")
print("必ず説明書を読んでからゲームを開始してください！")
Person.explain_contents()
character = str(input("どんな人ですか？："))
if character == "究極の凡人":
    name = str(input("お名前は？"))
    person = CommonPerson(name)
    
elif character == "通りすがりの天才":
    name = str(input("お名前は？"))
    person = GeniusPerson(name, 2, 7)
    
elif character == "幸せ者":
    name = str(input("お名前は？"))
    person = HappyPerson(name, 20, 3)

else:
    name = str(input("お名前は？"))
    person = CommonPerson(name)
    person = CommonPerson(name)

print(person)   

print("***********************************************{}さんの登録完了！***************************************************************".format(person.name))

for i in range(1, 11):
    print("***********************************************{}ターン目開始***************************************************************".format(i))
    print("{}ターン目です。何をしますか？【勉強】、【稼ぐ】、【遊ぶ】、【賭ける】 、または【スキル】　のどれかを入れてください。".format(i))
    print("＊上記の行動以外の文字を入れた場合、自動で「何もしない」が選択されます")
    print("＊スキルは1度しか使えません。間違って再度使用すると、そのターンは「何もしない」が選択されます")
    act = str(input("何をする？"))
    if act == "勉強":
        person.study()
    elif act == "稼ぐ":
        person.earn()
    elif act == "遊ぶ":
        person.play()
    elif act == "賭ける":
        person.bet()
    elif act == "スキル" and person.skill >= 1:
        person.skill_something()
        person.skill -= 1
    else:
        person.boring()
    
    if person.hapiness <= 0:
        import sys
        print("幸せ度が0になりました")
        print("あなたは絶望的な状態です。")
        print("自分の行いを振り返ってみましょう")
        print("ゲームオーバー")
        sys.exit()
    elif person.ability <= 0:
        import sys
        print("能力が0になりました")
        print("あなたは今は幸せかもしれません")
        print("しかし未来はどうでしょうか？よく考えてみてください")
        print("ゲームオーバー")
        sys.exit()
    else:
        pass
    print("***********************************************{}ターン目終わり***************************************************************".format(i))
    print("**************************************************************************************************************")
    
    
print("結果的に私は、幸せは{}pointで終わった。".format(person.hapiness))
if person.hapiness <= 10:
    print("私はこれでいいのだろうか？")
    print("幸せ評価：　泣")
elif person.hapiness <= 30:
    print("私は幸せだったのだろうか、きっと幸せだったのだろう")
    print("幸せ評価：　普通")
elif person.hapiness <= 60:
    print("私は胸を張って言える。幸せだと。")
    print("幸せ評価：　幸せ")
elif person.hapiness <= 100:
    print("世界で1番幸せかもしれない。そんな人生。")
    print("幸せ評価：　超幸福")
else:
    print("次元を超えた幸せを手にした。")
    print("幸せ評価：　誰も体験したことのない最上級の幸せ")
# お終い